"""The divoom-gateway TCP wire protocol.

Byte-for-byte the protocol the ESP32 `divoom-gateway` firmware speaks, so that
Home Assistant's `custom_components/divoom` cannot tell a Raspberry Pi gateway
from an ESP32 one. See docs/PROTOCOL.md for the long version.

Client -> gateway::

    0x69 <mac:6> [<channel:1>]    connect to that Divoom over RFCOMM
    0x96 <mac:6>                  disconnect
    0x01 ... 0x02                 raw Divoom payload, relayed verbatim

Gateway -> client::

    <bytes>                       whatever the Divoom device sent back
    0x69                          payload dropped: Bluetooth still connecting
    0x96                          payload dropped: no Bluetooth connection
    0x00 <mac:6> <len:1> <name>   a Divoom device we discovered over Bluetooth

The two single-byte replies are what the integration's reconnect() looks for:
a trailing 0x69 makes it wait and retry the ping, a trailing 0x96 makes it
treat the link as dead (errno 696) and run its reconnect loop.
"""

from __future__ import annotations

from typing import List, NamedTuple, Union

CMD_CONNECT = 0x69
CMD_DISCONNECT = 0x96
FRAME_START = 0x01
FRAME_END = 0x02
ADVERTISE = 0x00

# RFCOMM channel used when a connect message carries no explicit channel byte.
DEFAULT_CHANNEL = 1

REPLY_CONNECTING = bytes([CMD_CONNECT])
REPLY_NOT_CONNECTED = bytes([CMD_DISCONNECT])

# A framed payload longer than this is treated as garbage and the parser
# resynchronises rather than buffering forever. The largest thing the
# integration sends in one go is an image/animation frame, far below this.
MAX_MESSAGE = 65536

# Shortest thing that can be a valid framed payload: 0x01, 2-byte length,
# command, 2-byte checksum, 0x02.
MIN_FRAME = 7


class Connect(NamedTuple):
    """Client asked us to open an RFCOMM link."""

    mac: str
    channel: int


class Disconnect(NamedTuple):
    """Client asked us to close the RFCOMM link."""

    mac: str


class Payload(NamedTuple):
    """A complete 0x01..0x02 framed message to relay to the Divoom device."""

    data: bytes


Message = Union[Connect, Disconnect, Payload]


def format_mac(raw: bytes) -> str:
    """6 raw address bytes -> AA:BB:CC:DD:EE:FF, the spelling BlueZ uses."""
    if len(raw) != 6:
        raise ValueError("a Bluetooth address is 6 bytes, got %d" % len(raw))
    return ":".join("%02X" % byte for byte in raw)


def parse_mac(mac: str) -> bytes:
    """AA:BB:CC:DD:EE:FF (or unseparated, or hyphenated) -> 6 raw bytes."""
    cleaned = mac.strip().replace(":", "").replace("-", "").replace(".", "")
    if len(cleaned) != 12:
        raise ValueError("not a Bluetooth address: %r" % (mac,))
    return bytes.fromhex(cleaned)


def normalize_mac(mac: str) -> str:
    """Normalise any accepted MAC spelling to BlueZ's upper-case colon form."""
    return format_mac(parse_mac(mac))


def advertisement(mac: str, name: str) -> bytes:
    """Build the 0x00 discovered-device notification sent to TCP clients."""
    encoded = name.encode("utf-8", "replace")[:255]
    return bytes([ADVERTISE]) + parse_mac(mac) + bytes([len(encoded)]) + encoded


def build_message(payload: bytes) -> bytes:
    """Wrap a raw payload the way the integration's make_message() does.

    Appends the little-endian sum-of-bytes checksum and frames the result
    between 0x01 and 0x02. Payload escaping is deliberately not applied: the
    integration defaults escapePayload to off for every device type.
    """
    total = sum(payload)
    checksum = total.to_bytes(4 if total >= 65535 else 2, byteorder="little")
    return bytes([FRAME_START]) + payload + checksum + bytes([FRAME_END])


def build_command(command: int, args: bytes = b"") -> bytes:
    """Build a complete Divoom command message (integration's send_command())."""
    length = len(args) + 3
    return build_message(length.to_bytes(2, byteorder="little") + bytes([command]) + args)


# The only commands divoom-pi itself ever builds, for `divoom-pi selftest`.
# Everything else is generated by Home Assistant and relayed untouched.
CMD_SET_VIEW = 0x45
CMD_GET_VIEW = 0x46


def ping() -> bytes:
    """"get view" - what the integration uses as its connectivity ping."""
    return build_command(CMD_GET_VIEW)


def light(color=None, brightness: int = 100, power: bool = True) -> bytes:
    """"set view" in light mode - hass-divoom's show_light().

    color=None takes the integration's own "no colour given" branch, which
    sends white with a different trailing flag; an explicit colour takes the
    custom-colour branch. The distinction matters more than it looks: send_on()
    passes (1, 1, 1), which is very nearly black, so a device switched "on"
    that way lights up showing essentially nothing.
    """
    args = bytes([0x01])
    if color is None or len(color) < 3:
        args += bytes([0xFF, 0xFF, 0xFF, brightness & 0xFF, 0x01])
    else:
        args += bytes(color[:3]) + bytes([brightness & 0xFF, 0x00])
    args += bytes([0x01 if power else 0x00, 0x00, 0x00, 0x00])
    return build_command(CMD_SET_VIEW, args)


def display_on() -> bytes:
    """Byte-for-byte what the integration's send_on() sends (near-black - see light())."""
    return light(color=(0x01, 0x01, 0x01), brightness=100, power=True)


def display_off() -> bytes:
    """Byte-for-byte what the integration's send_off() sends."""
    return light(color=(0x01, 0x01, 0x01), brightness=0, power=False)


def clock(
    style: int = 0,
    twentyfour: bool = False,
    weather: bool = False,
    temperature: bool = False,
    calendar: bool = False,
    color=None,
) -> bytes:
    """"set view" in clock mode - hass-divoom's show_clock().

    The integration also sends a separate "set time type" command when the
    caller specifies twentyfour; this builds only the view command, which is
    all that is needed to put a display back to something recognisable.
    """
    args = bytes([0x00, 0x01 if twentyfour else 0x00])
    if 0 <= style <= 15:
        args += bytes([style, 0x01])  # clock style, clock activated
    else:
        args += bytes([0x00, 0x00])  # style 0, clock deactivated
    args += bytes(
        [
            0x01 if weather else 0x00,
            0x01 if temperature else 0x00,
            0x01 if calendar else 0x00,
        ]
    )
    if color is not None and len(color) == 3:
        args += bytes(color)
    return build_command(CMD_SET_VIEW, args)


def strip_advertisements(data: bytes) -> bytes:
    """Drop any 0x00 discovered-device notifications from the front of data.

    The gateway announces the devices it finds to its TCP clients, so bytes
    read back off the socket can begin with one of those rather than with
    anything the Divoom said. Mistaking an advertisement for a device response
    makes a connectivity test claim success when nothing reached the device.
    """
    while len(data) >= 8 and data[0] == ADVERTISE:
        end = 8 + data[7]
        if len(data) < end:
            break
        data = data[end:]
    return data


def hexdump(data: bytes, limit: int = 64) -> str:
    """Compact hex rendering for debug logs, truncated to keep lines readable."""
    shown = data[:limit]
    text = " ".join("%02x" % byte for byte in shown)
    if len(data) > limit:
        text += " ... (%d bytes total)" % len(data)
    return text


class MessageParser:
    """Turns a client's TCP byte stream into protocol messages.

    Framing follows the ESP32 firmware rather than trying to be cleverer than
    it: a payload message ends at the first read whose last byte is 0x02, and
    an incomplete tail is carried over into the next read. That matters because
    the Divoom payload is *not* escaped by default, so a 0x02 can legitimately
    appear inside a payload and scanning for a terminator would split frames in
    the wrong place. The integration sends each message with its own sendall(),
    so in practice reads line up with messages.
    """

    def __init__(self, logger, max_message: int = MAX_MESSAGE):
        self._log = logger
        self._max_message = max_message
        self._buffer = bytearray()

    def reset(self) -> None:
        self._buffer.clear()

    @property
    def pending(self) -> int:
        return len(self._buffer)

    def feed(self, data: bytes) -> List[Message]:
        """Feed one TCP read; return the messages that completed."""
        self._buffer.extend(data)
        messages: List[Message] = []
        buffer = self._buffer

        while buffer:
            head = buffer[0]

            if head == CMD_CONNECT:
                if len(buffer) < 7:
                    break
                # The integration always appends the RFCOMM channel, so a
                # buffer longer than 7 bytes has it at index 7 and anything
                # after that is the start of the next message.
                if len(buffer) == 7:
                    channel, consumed = DEFAULT_CHANNEL, 7
                else:
                    channel, consumed = buffer[7], 8
                messages.append(Connect(format_mac(bytes(buffer[1:7])), channel))
                del buffer[:consumed]
                continue

            if head == CMD_DISCONNECT:
                if len(buffer) < 7:
                    break
                messages.append(Disconnect(format_mac(bytes(buffer[1:7]))))
                del buffer[:7]
                continue

            if head == FRAME_START:
                if len(buffer) < MIN_FRAME:
                    break
                if buffer[-1] != FRAME_END:
                    if len(buffer) > self._max_message:
                        self._log.warning(
                            "dropping %d buffered bytes: no frame terminator within %d bytes",
                            len(buffer),
                            self._max_message,
                        )
                        buffer.clear()
                    break
                messages.append(Payload(bytes(buffer)))
                buffer.clear()
                continue

            # Nothing we recognise - drop a byte and try to resynchronise.
            self._log.warning("unexpected leading byte 0x%02x, resynchronising", head)
            del buffer[:1]

        return messages
